In [102]:
from numpy import random
import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from numpy import random
import pandas as pd
import sklearn.preprocessing as pre

In [183]:
# Creating covariates with different probability distribution

np.random.seed(42)

noise = random.normal(loc = 0, scale = 10, size = 100).reshape(-1,1)
approx_coefs = np.random.rand(3).reshape(3,1)
inter = np.random.rand(1)

c1 = random.normal(loc = 0, scale = 5, size = 100).reshape(-1,1)
c2 = 100 * random.gamma(shape = 10, scale = 10, size = 100).reshape(-1,1)
c3 = 20 * random.uniform(low = 0,high = 100, size = 100).reshape(-1,1)

print('approx coefs:\n', approx_coefs)

X = np.hstack((c1,c2,c3))
y = np.dot(X , approx_coefs) + inter + noise * 10


data = pd.DataFrame(data = np.hstack((X,y)))
data.columns = ['c1','c2','c3','y']
data

approx coefs:
 [[0.417411  ]
 [0.22210781]
 [0.11986537]]


c1            c2            c3              y
0    -0.524442   5984.827967  3.797781e+06  456601.477560
1     8.245521   7034.196361  3.890447e+06  467882.105332
2   838.809800  11358.067278  1.949719e+06  236641.748363
3     0.665085  27274.388513  1.149597e+06  144007.670309
4     2.135486  12946.494783  3.832294e+05   48789.261786
..         ...           ...           ...            ...
95 -186.644350   7471.777854  4.779435e+05   58724.490094
96    5.725125  18198.540192  3.216918e+06  389671.412095
97   22.044390   7365.056307  8.985585e+05  109377.531402
98  158.802388   4452.721478  1.782533e+06  214720.132272
99  146.280735   8122.436119  1.187766e+05   16079.189633

[100 rows x 4 columns]

In [184]:
# Using regression model without normalization

X = np.hstack((c1,c2,c3))
y = np.dot(X , approx_coefs) + noise * 20


Model = LinearRegression()
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.4, random_state=42)
Model.fit(X_train,y_train)
print(Model.coef_)
print(Model.score(X_train, y_train))
print(Model.rank_)

data = pd.DataFrame(data = np.hstack((X,y)))
data.columns = ['c1','c2','c3','y']
data

[[0.42338397 0.23412346 0.11983176]]
0.9999983776883614
3


c1            c2            c3              y
0    -0.524442   5984.827967  3.797781e+06  456650.811360
1     8.245521   7034.196361  3.890447e+06  467867.941287
2   838.809800  11358.067278  1.949719e+06  236706.179602
3     0.665085  27274.388513  1.149597e+06  144159.635679
4     2.135486  12946.494783  3.832294e+05   48765.508834
..         ...           ...           ...            ...
95 -186.644350   7471.777854  4.779435e+05   58577.800984
96    5.725125  18198.540192  3.216918e+06  389700.686508
97   22.044390   7365.056307  8.985585e+05  109403.299314
98  158.802388   4452.721478  1.782533e+06  214720.306002
99  146.280735   8122.436119  1.187766e+05   16055.393305

[100 rows x 4 columns]

In [185]:
X = np.hstack((c1,c2,c3))
y = np.dot(X , approx_coefs) + inter + noise * 20


# min max normalization
S = pre.MinMaxScaler()
X = S.fit_transform(X)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.4, random_state=42)

Model = LinearRegression()
Model.fit(X_train,y_train)
print(Model.coef_)
print(Model.score(X_train, y_train))
print(Model.rank_)

data = pd.DataFrame(data = np.hstack((X,y)))
data.columns = ['c1','c2','c3','y']
data

[[  1439.06677213   5756.84644736 478955.01015098]]
0.9999983776883614
3


c1        c2        c3              y
0   0.259642  0.134181  0.949971  456651.148975
1   0.262222  0.176858  0.973155  467868.278902
2   0.506580  0.352704  0.487597  236706.517217
3   0.259992  1.000000  0.287411  144159.973295
4   0.260425  0.417303  0.095670   48765.846449
..       ...       ...       ...            ...
95  0.204884  0.194654  0.119367   58578.138599
96  0.261481  0.630897  0.804642  389701.024123
97  0.266282  0.190313  0.224602  109403.636929
98  0.306517  0.071872  0.445768  214720.643617
99  0.302833  0.221115  0.029505   16055.730920

[100 rows x 4 columns]

In [186]:
X = np.hstack((c1,c2,c3))
y = np.dot(X , approx_coefs) + inter + noise * 20


# min max normalization
S = pre.StandardScaler()
X = S.fit_transform(X)
# y = S.fit_transform(y)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.4, random_state=42)

Model = LinearRegression()
Model.fit(X_train,y_train)
print(Model.coef_)
print(Model.score(X_train, y_train))
print(Model.rank_)

data = pd.DataFrame(data = np.hstack((X,y)))
data.columns = ['c1','c2','c3','y']
data


[[   170.10754738    840.9740314  153905.14675568]]
0.9999983776883614
3


c1        c2        c3              y
0  -0.140436 -1.168401  1.766732  456651.148975
1  -0.118608 -0.876261  1.838882  467868.278902
2   1.948600  0.327486  0.327816  236706.517217
3  -0.137475  4.758519 -0.295165  144159.973295
4  -0.133815  0.769697 -0.891865   48765.846449
..       ...       ...       ...            ...
95 -0.603673 -0.754440 -0.818120   58578.138599
96 -0.124881  2.231843  1.314467  389701.024123
97 -0.084264 -0.784151 -0.490626  109403.636929
98  0.256116 -1.594932  0.197644  214720.643617
99  0.224951 -0.573300 -1.097770   16055.730920

[100 rows x 4 columns]

In [189]:
X = np.hstack((c1,c2,c3))
y = np.dot(X , approx_coefs) + inter + noise * 20


# min max normalization
S = pre.MaxAbsScaler()
X = S.fit_transform(X)
# y = S.fit_transform(y)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.4, random_state=42)

Model = LinearRegression()
Model.fit(X_train,y_train)
print(Model.coef_)
print(Model.score(X_train, y_train))
print(Model.rank_)

data = pd.DataFrame(data = np.hstack((X,y)))
data.columns = ['c1','c2','c3','y']
data


[[  1065.20246415   6385.57408071 479056.41048884]]
0.9999983776883614
3


c1        c2        c3              y
0  -0.000208  0.219430  0.949982  456651.148975
1   0.003277  0.257905  0.973161  467868.278902
2   0.333400  0.416437  0.487705  236706.517217
3   0.000264  1.000000  0.287562  144159.973295
4   0.000849  0.474676  0.095861   48765.846449
..       ...       ...       ...            ...
95 -0.074185  0.273949  0.119553   58578.138599
96  0.002276  0.667239  0.804684  389701.024123
97  0.008762  0.270036  0.224767  109403.636929
98  0.063119  0.163257  0.445885  214720.643617
99  0.058142  0.297805  0.029711   16055.730920

[100 rows x 4 columns]

In [190]:
X = np.hstack((c1,c2,c3))
y = np.dot(X , approx_coefs) + inter + noise * 20


# min max normalization
S = pre.Normalizer()
X = S.fit_transform(X)
# y = S.fit_transform(y)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.4, random_state=42)

Model = LinearRegression()
Model.fit(X_train,y_train)
print(Model.coef_)
print(Model.score(X_train, y_train))
print(Model.rank_)

data = pd.DataFrame(data = np.hstack((X,y)))
data.columns = ['c1','c2','c3','y']
data


[[  128858.95977513 -2166485.05110661 -2508970.47722227]]
0.4355664297456874
3


c1        c2        c3              y
0  -1.380916e-07  0.001576  0.999999  456651.148975
1   2.119424e-06  0.001808  0.999998  467868.278902
2   4.302135e-04  0.005825  0.999983  236706.517217
3   5.783746e-07  0.023718  0.999719  144159.973295
4   5.569166e-06  0.033763  0.999430   48765.846449
..           ...       ...       ...            ...
95 -3.904678e-04  0.015631  0.999878   58578.138599
96  1.779664e-06  0.005657  0.999984  389701.024123
97  2.453223e-05  0.008196  0.999966  109403.636929
98  8.908775e-05  0.002498  0.999997  214720.643617
99  1.228692e-03  0.068225  0.997669   16055.730920

[100 rows x 4 columns]

In [193]:
X = np.hstack((c1,c2,c3))
y = np.dot(X , approx_coefs) + inter + noise * 20


# min max normalization
S = pre.Normalizer()
X = S.fit_transform(X)
y = S.fit_transform(y)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.4, random_state=42)

Model = LinearRegression()
Model.fit(X_train,y_train)
print(Model.coef_)
print(Model.score(X_train, y_train))
print(Model.rank_)

data = pd.DataFrame(data = np.hstack((X,y)))
data.columns = ['c1','c2','c3','y']
data


[[0. 0. 0.]]
1.0
3


c1        c2        c3    y
0  -1.380916e-07  0.001576  0.999999  1.0
1   2.119424e-06  0.001808  0.999998  1.0
2   4.302135e-04  0.005825  0.999983  1.0
3   5.783746e-07  0.023718  0.999719  1.0
4   5.569166e-06  0.033763  0.999430  1.0
..           ...       ...       ...  ...
95 -3.904678e-04  0.015631  0.999878  1.0
96  1.779664e-06  0.005657  0.999984  1.0
97  2.453223e-05  0.008196  0.999966  1.0
98  8.908775e-05  0.002498  0.999997  1.0
99  1.228692e-03  0.068225  0.997669  1.0

[100 rows x 4 columns]

In [192]:
X = np.hstack((c1,c2,c3))
y = np.dot(X , approx_coefs) + inter + noise * 20


# min max normalization
S = pre.QuantileTransformer(n_quantiles = 10, output_distribution='normal', random_state=0)
X = S.fit_transform(X)
# y = S.fit_transform(y)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.4, random_state=42)

Model = LinearRegression()
Model.fit(X_train,y_train)
print(Model.coef_)
print(Model.score(X_train, y_train))
print(Model.rank_)

data = pd.DataFrame(data = np.hstack((X,y)))
data.columns = ['c1','c2','c3','y']
data


[[ -5427.74832321  -2194.43460036 135300.90311657]]
0.885253894887788
3


c1        c2        c3              y
0  -0.223081 -1.348837  1.717903  456651.148975
1   0.405787 -1.072556  1.994968  467868.278902
2   1.405078  0.488593  0.409592  236706.517217
3  -0.055028  5.199338 -0.046036  144159.973295
4   0.139710  0.923711 -0.631866   48765.846449
..       ...       ...       ...            ...
95 -1.220640 -0.827702 -0.547184   58578.138599
96  0.293624  1.443287  1.008778  389701.024123
97  0.524021 -0.882499 -0.197073  109403.636929
98  1.106588 -1.669510  0.305662  214720.643617
99  1.059600 -0.496884 -1.080025   16055.730920

[100 rows x 4 columns]

In [194]:
X = np.hstack((c1,c2,c3))
y = np.dot(X , approx_coefs) + inter + noise * 20


# min max normalization
S = pre.QuantileTransformer(n_quantiles = 10, output_distribution='normal', random_state=0)
X = S.fit_transform(X)
y = S.fit_transform(y)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.4, random_state=42)

Model = LinearRegression()
Model.fit(X_train,y_train)
print(Model.coef_)
print(Model.score(X_train, y_train))
print(Model.rank_)

data = pd.DataFrame(data = np.hstack((X,y)))
data.columns = ['c1','c2','c3','y']
data


[[-0.00276969  0.01837143  0.98567277]]
0.9889228448692737
3


c1        c2        c3         y
0  -0.223081 -1.348837  1.717903  1.715756
1   0.405787 -1.072556  1.994968  1.998643
2   1.405078  0.488593  0.409592  0.414041
3  -0.055028  5.199338 -0.046036 -0.026441
4   0.139710  0.923711 -0.631866 -0.628603
..       ...       ...       ...       ...
95 -1.220640 -0.827702 -0.547184 -0.554805
96  0.293624  1.443287  1.008778  1.019813
97  0.524021 -0.882499 -0.197073 -0.199077
98  1.106588 -1.669510  0.305662  0.300901
99  1.059600 -0.496884 -1.080025 -1.093384

[100 rows x 4 columns]