In [3]:
import numpy as np

In [4]:
def sigmoid(x):
    return 1/(1+np.exp(-x))

def sigmoid_derivative(x):
    return sigmoid(x) * (1 - sigmoid(x))

In [6]:
def test(inputs, weights, bias):
    X = sigmoid(np.dot(inputs, weights) + bias)
    

In [33]:
class NeuralNetwork:
    def __init__(self, x, y):
        self.input      = x
        self.weights1   = np.random.rand(self.input.shape[1],4) 
        self.weights2   = np.random.rand(4,1)                 
        self.y          = y
        self.output     = np.zeros(self.y.shape)

    def feedforward(self):
        self.layer1 = sigmoid(np.dot(self.input, self.weights1))
        self.output = sigmoid(np.dot(self.layer1, self.weights2))

    def backprop(self):
        d_weights2 = np.dot(self.layer1.T, (2*(self.y - self.output) * sigmoid_derivative(self.output)))
        d_weights1 = np.dot(self.input.T,  (np.dot(2*(self.y - self.output) * sigmoid_derivative(self.output), self.weights2.T) * sigmoid_derivative(self.layer1)))
        self.weights1 += d_weights1
        self.weights2 += d_weights2

In [34]:
x = np.array([0,0,1,0,1,1,1,0,1,1,1,1]).reshape(4,3)
y = np.array([0,1,1,0]).reshape(4,1)

m = NeuralNetwork(x,y)

In [35]:
for i in range(10000):
    m.feedforward()
    m.backprop()
    print(m.output)
    

[[0.70313627]
 [0.72271738]
 [0.74107939]
 [0.7548151 ]]
[[0.52647459]
 [0.52561922]
 [0.53431296]
 [0.53443278]]
[[0.50323936]
 [0.49955917]
 [0.50629503]
 [0.50432634]]
[[0.50321943]
 [0.49971065]
 [0.5063091 ]
 [0.50446123]]
[[0.50313475]
 [0.49978791]
 [0.50624481]
 [0.50451074]]
[[0.50305125]
 [0.4998654 ]
 [0.50618182]
 [0.50456082]]
[[0.50296824]
 [0.49994236]
 [0.50611928]
 [0.50461057]]
[[0.5028857 ]
 [0.50001881]
 [0.50605719]
 [0.50466003]]
[[0.50280362]
 [0.50009476]
 [0.50599554]
 [0.50470919]]
[[0.502722  ]
 [0.50017024]
 [0.50593432]
 [0.50475807]]
[[0.5026408 ]
 [0.50024525]
 [0.50587352]
 [0.50480668]]
[[0.50256002]
 [0.50031981]
 [0.50581312]
 [0.50485502]]
[[0.50247965]
 [0.50039393]
 [0.50575312]
 [0.50490311]]
[[0.50239968]
 [0.50046762]
 [0.50569351]
 [0.50495095]]
[[0.50232008]
 [0.50054089]
 [0.50563427]
 [0.50499855]]
[[0.50224084]
 [0.50061377]
 [0.50557539]
 [0.50504592]]
[[0.50216197]
 [0.50068625]
 [0.50551687]
 [0.50509307]]
[[0.50208343]
 [0.50075835]
 [0

[[0.49178341]
 [0.50520145]
 [0.49881245]
 [0.5152085 ]]
[[0.49181358]
 [0.50520992]
 [0.49881053]
 [0.51517356]]
[[0.49184365]
 [0.50521846]
 [0.49880856]
 [0.51513865]]
[[0.49187364]
 [0.50522706]
 [0.49880655]
 [0.51510378]]
[[0.49190354]
 [0.50523572]
 [0.4988045 ]
 [0.51506895]]
[[0.49193334]
 [0.50524445]
 [0.49880241]
 [0.51503415]]
[[0.49196306]
 [0.50525324]
 [0.49880027]
 [0.51499939]]
[[0.49199269]
 [0.5052621 ]
 [0.49879808]
 [0.51496466]]
[[0.49202224]
 [0.50527102]
 [0.49879586]
 [0.51492997]]
[[0.49205169]
 [0.50528   ]
 [0.49879358]
 [0.51489531]]
[[0.49208107]
 [0.50528906]
 [0.49879127]
 [0.51486068]]
[[0.49211035]
 [0.50529817]
 [0.49878891]
 [0.51482609]]
[[0.49213956]
 [0.50530736]
 [0.4987865 ]
 [0.51479153]]
[[0.49216868]
 [0.50531661]
 [0.49878404]
 [0.514757  ]]
[[0.49219772]
 [0.50532593]
 [0.49878155]
 [0.51472251]]
[[0.49222667]
 [0.50533532]
 [0.498779  ]
 [0.51468804]]
[[0.49225555]
 [0.50534477]
 [0.49877641]
 [0.51465361]]
[[0.49228434]
 [0.50535429]
 [0

[[0.46952766]
 [0.51028292]
 [0.50028485]
 [0.52114918]]
[[0.46957448]
 [0.51026449]
 [0.50026381]
 [0.52113544]]
[[0.46962113]
 [0.51024626]
 [0.50024301]
 [0.52112127]]
[[0.4696676 ]
 [0.51022823]
 [0.50022246]
 [0.52110668]]
[[0.46971388]
 [0.51021041]
 [0.50020215]
 [0.52109165]]
[[0.46975996]
 [0.51019279]
 [0.50018208]
 [0.5210762 ]]
[[0.46980583]
 [0.51017539]
 [0.50016227]
 [0.52106033]]
[[0.46985147]
 [0.51015821]
 [0.5001427 ]
 [0.52104403]]
[[0.46989687]
 [0.51014125]
 [0.50012338]
 [0.52102731]]
[[0.46994203]
 [0.51012453]
 [0.50010431]
 [0.52101017]]
[[0.46998692]
 [0.51010803]
 [0.5000855 ]
 [0.52099261]]
[[0.47003155]
 [0.51009177]
 [0.50006694]
 [0.52097463]]
[[0.47007589]
 [0.51007576]
 [0.50004863]
 [0.52095622]]
[[0.47011994]
 [0.51005998]
 [0.50003057]
 [0.5209374 ]]
[[0.47016369]
 [0.51004447]
 [0.50001277]
 [0.52091817]]
[[0.47020712]
 [0.5100292 ]
 [0.49999523]
 [0.52089851]]
[[0.47025023]
 [0.5100142 ]
 [0.49997795]
 [0.52087844]]
[[0.47029301]
 [0.50999946]
 [0

[[0.39755398]
 [0.97000208]
 [0.81461164]
 [0.40559239]]
[[0.02852473]
 [0.57871033]
 [0.62441901]
 [0.1044297 ]]
[[0.39572457]
 [0.97025042]
 [0.81504611]
 [0.40362047]]
[[0.02846726]
 [0.58011284]
 [0.62597598]
 [0.10430826]]
[[0.39387091]
 [0.97049064]
 [0.81547903]
 [0.40162434]]
[[0.02841652]
 [0.5815382 ]
 [0.62755788]
 [0.10418805]]
[[0.39199303]
 [0.9707228 ]
 [0.81591062]
 [0.39960411]]
[[0.02837249]
 [0.58298643]
 [0.6291646 ]
 [0.10406898]]
[[0.39009102]
 [0.97094692]
 [0.81634112]
 [0.39755993]]
[[0.02833514]
 [0.58445751]
 [0.630796  ]
 [0.10395095]]
[[0.388165  ]
 [0.97116308]
 [0.81677076]
 [0.395492  ]]
[[0.02830447]
 [0.5859514 ]
 [0.63245187]
 [0.10383389]]
[[0.38621517]
 [0.97137132]
 [0.81719977]
 [0.39340059]]
[[0.02828046]
 [0.587468  ]
 [0.63413199]
 [0.1037177 ]]
[[0.38424173]
 [0.97157169]
 [0.81762839]
 [0.39128599]]
[[0.02826307]
 [0.5890072 ]
 [0.63583607]
 [0.10360229]]
[[0.38224496]
 [0.97176426]
 [0.81805683]
 [0.38914856]]
[[0.02825229]
 [0.59056881]
 [0

[[0.03844805]
 [0.88096541]
 [0.9011163 ]
 [0.05445669]]
[[0.07060975]
 [0.97783166]
 [0.93717258]
 [0.08353106]]
[[0.03841867]
 [0.88116305]
 [0.90126119]
 [0.05439404]]
[[0.07045618]
 [0.97784929]
 [0.93728994]
 [0.08337257]]
[[0.0383893 ]
 [0.88135974]
 [0.90140539]
 [0.0543316 ]]
[[0.07030347]
 [0.97786693]
 [0.93740684]
 [0.08321488]]
[[0.03835993]
 [0.88155548]
 [0.90154891]
 [0.05426936]]
[[0.07015162]
 [0.97788458]
 [0.93752327]
 [0.08305798]]
[[0.03833056]
 [0.88175026]
 [0.90169173]
 [0.05420731]]
[[0.07000062]
 [0.97790226]
 [0.93763923]
 [0.08290187]]
[[0.03830119]
 [0.88194411]
 [0.90183387]
 [0.05414545]]
[[0.06985046]
 [0.97791996]
 [0.93775473]
 [0.08274655]]
[[0.03827183]
 [0.88213701]
 [0.90197534]
 [0.05408379]]
[[0.06970115]
 [0.97793768]
 [0.93786978]
 [0.082592  ]]
[[0.03824246]
 [0.88232898]
 [0.90211612]
 [0.05402232]]
[[0.06955267]
 [0.97795542]
 [0.93798437]
 [0.08243823]]
[[0.0382131 ]
 [0.88252003]
 [0.90225623]
 [0.05396105]]
[[0.06940502]
 [0.97797318]
 [0

[[0.02869843]
 [0.91603263]
 [0.92625897]
 [0.03887557]]
[[0.0447932 ]
 [0.98701157]
 [0.96521743]
 [0.05426123]]
[[0.02868011]
 [0.91606698]
 [0.92628019]
 [0.03885108]]
[[0.0447688 ]
 [0.98703433]
 [0.96526343]
 [0.05422861]]
[[0.02866183]
 [0.9161012 ]
 [0.9263013 ]
 [0.03882663]]
[[0.04474449]
 [0.98705705]
 [0.96530935]
 [0.05419609]]
[[0.02864358]
 [0.9161353 ]
 [0.92632231]
 [0.03880225]]
[[0.04472026]
 [0.98707975]
 [0.96535518]
 [0.05416367]]
[[0.02862537]
 [0.91616928]
 [0.92634323]
 [0.03877792]]
[[0.04469612]
 [0.98710241]
 [0.96540092]
 [0.05413135]]
[[0.0286072 ]
 [0.91620313]
 [0.92636405]
 [0.03875364]]
[[0.04467207]
 [0.98712504]
 [0.96544656]
 [0.05409914]]
[[0.02858906]
 [0.91623686]
 [0.92638477]
 [0.03872942]]
[[0.04464811]
 [0.98714764]
 [0.96549212]
 [0.05406703]]
[[0.02857095]
 [0.91627047]
 [0.92640539]
 [0.03870526]]
[[0.04462423]
 [0.9871702 ]
 [0.96553759]
 [0.05403501]]
[[0.02855288]
 [0.91630396]
 [0.92642592]
 [0.03868115]]
[[0.04460045]
 [0.98719273]
 [0

[[0.02346761]
 [0.92808523]
 [0.93468761]
 [0.03175515]]
[[0.03706   ]
 [0.99234666]
 [0.97725523]
 [0.04388102]]
[[0.02345637]
 [0.92814761]
 [0.93474469]
 [0.03173714]]
[[0.0370264 ]
 [0.99234243]
 [0.97726735]
 [0.04383923]]
[[0.0234451 ]
 [0.92821042]
 [0.93480221]
 [0.03171908]]
[[0.03699261]
 [0.99233803]
 [0.97727935]
 [0.04379722]]
[[0.02343381]
 [0.92827365]
 [0.93486015]
 [0.03170096]]
[[0.03695862]
 [0.99233348]
 [0.97729123]
 [0.043755  ]]
[[0.0234225 ]
 [0.9283373 ]
 [0.93491853]
 [0.0316828 ]]
[[0.03692444]
 [0.99232876]
 [0.97730299]
 [0.04371255]]
[[0.02341117]
 [0.92840139]
 [0.93497733]
 [0.03166458]]
[[0.03689007]
 [0.99232387]
 [0.97731463]
 [0.04366988]]
[[0.02339982]
 [0.92846591]
 [0.93503657]
 [0.03164631]]
[[0.0368555 ]
 [0.99231882]
 [0.97732615]
 [0.043627  ]]
[[0.02338844]
 [0.92853086]
 [0.93509624]
 [0.03162799]]
[[0.03682074]
 [0.9923136 ]
 [0.97733755]
 [0.04358389]]
[[0.02337704]
 [0.92859624]
 [0.93515635]
 [0.03160961]]
[[0.03678579]
 [0.99230821]
 [0

[[0.01731666]
 [0.97684107]
 [0.97517199]
 [0.02128632]]
[[0.01730138]
 [0.97686119]
 [0.97519402]
 [0.02126745]]
[[0.0172861 ]
 [0.97688131]
 [0.97521605]
 [0.02124859]]
[[0.01727084]
 [0.97690141]
 [0.97523805]
 [0.02122974]]
[[0.01725558]
 [0.97692149]
 [0.97526004]
 [0.0212109 ]]
[[0.01724034]
 [0.97694157]
 [0.97528202]
 [0.02119208]]
[[0.01722511]
 [0.97696163]
 [0.97530397]
 [0.02117327]]
[[0.01720988]
 [0.97698168]
 [0.97532592]
 [0.02115448]]
[[0.01719467]
 [0.97700171]
 [0.97534784]
 [0.0211357 ]]
[[0.01717947]
 [0.97702173]
 [0.97536975]
 [0.02111693]]
[[0.01716428]
 [0.97704174]
 [0.97539165]
 [0.02109817]]
[[0.0171491 ]
 [0.97706173]
 [0.97541352]
 [0.02107943]]
[[0.01713393]
 [0.97708171]
 [0.97543538]
 [0.0210607 ]]
[[0.01711877]
 [0.97710167]
 [0.97545723]
 [0.02104199]]
[[0.01710362]
 [0.97712162]
 [0.97547905]
 [0.02102329]]
[[0.01708848]
 [0.97714155]
 [0.97550086]
 [0.02100461]]
[[0.01707336]
 [0.97716148]
 [0.97552266]
 [0.02098593]]
[[0.01705824]
 [0.97718138]
 [0

[[0.0093374 ]
 [0.98739949]
 [0.98658839]
 [0.01147364]]
[[0.00933247]
 [0.98740605]
 [0.98659541]
 [0.01146759]]
[[0.00932755]
 [0.98741261]
 [0.98660242]
 [0.01146155]]
[[0.00932263]
 [0.98741916]
 [0.98660942]
 [0.01145552]]
[[0.00931772]
 [0.9874257 ]
 [0.9866164 ]
 [0.0114495 ]]
[[0.00931282]
 [0.98743223]
 [0.98662338]
 [0.01144349]]
[[0.00930792]
 [0.98743875]
 [0.98663035]
 [0.01143748]]
[[0.00930303]
 [0.98744526]
 [0.98663731]
 [0.01143148]]
[[0.00929815]
 [0.98745177]
 [0.98664426]
 [0.01142549]]
[[0.00929327]
 [0.98745826]
 [0.9866512 ]
 [0.01141951]]
[[0.00928841]
 [0.98746475]
 [0.98665813]
 [0.01141354]]
[[0.00928354]
 [0.98747122]
 [0.98666505]
 [0.01140758]]
[[0.00927869]
 [0.98747769]
 [0.98667196]
 [0.01140162]]
[[0.00927384]
 [0.98748415]
 [0.98667886]
 [0.01139567]]
[[0.00926899]
 [0.9874906 ]
 [0.98668576]
 [0.01138973]]
[[0.00926416]
 [0.98749704]
 [0.98669264]
 [0.0113838 ]]
[[0.00925933]
 [0.98750348]
 [0.98669951]
 [0.01137788]]
[[0.0092545 ]
 [0.9875099 ]
 [0

[[0.00681686]
 [0.99076221]
 [0.99016612]
 [0.00838818]]
[[0.00681507]
 [0.99076459]
 [0.99016864]
 [0.00838601]]
[[0.00681329]
 [0.99076697]
 [0.99017115]
 [0.00838384]]
[[0.00681151]
 [0.99076934]
 [0.99017367]
 [0.00838167]]
[[0.00680974]
 [0.99077172]
 [0.99017618]
 [0.0083795 ]]
[[0.00680796]
 [0.99077409]
 [0.99017869]
 [0.00837734]]
[[0.00680619]
 [0.99077645]
 [0.99018119]
 [0.00837517]]
[[0.00680442]
 [0.99077882]
 [0.99018369]
 [0.00837301]]
[[0.00680265]
 [0.99078118]
 [0.99018619]
 [0.00837086]]
[[0.00680088]
 [0.99078354]
 [0.99018869]
 [0.0083687 ]]
[[0.00679912]
 [0.9907859 ]
 [0.99019119]
 [0.00836655]]
[[0.00679735]
 [0.99078825]
 [0.99019368]
 [0.0083644 ]]
[[0.00679559]
 [0.9907906 ]
 [0.99019617]
 [0.00836225]]
[[0.00679383]
 [0.99079295]
 [0.99019865]
 [0.0083601 ]]
[[0.00679207]
 [0.9907953 ]
 [0.99020114]
 [0.00835796]]
[[0.00679032]
 [0.99079764]
 [0.99020362]
 [0.00835582]]
[[0.00678856]
 [0.99079999]
 [0.99020609]
 [0.00835368]]
[[0.00678681]
 [0.99080232]
 [0

[[0.00584573]
 [0.99205741]
 [0.99153243]
 [0.00720852]]
[[0.00584492]
 [0.99205848]
 [0.99153356]
 [0.00720755]]
[[0.00584412]
 [0.99205955]
 [0.99153469]
 [0.00720658]]
[[0.00584331]
 [0.99206062]
 [0.99153581]
 [0.00720561]]
[[0.00584251]
 [0.99206169]
 [0.99153693]
 [0.00720463]]
[[0.0058417 ]
 [0.99206276]
 [0.99153806]
 [0.00720366]]
[[0.0058409 ]
 [0.99206383]
 [0.99153918]
 [0.00720269]]
[[0.0058401 ]
 [0.9920649 ]
 [0.9915403 ]
 [0.00720173]]
[[0.0058393 ]
 [0.99206596]
 [0.99154142]
 [0.00720076]]
[[0.0058385 ]
 [0.99206703]
 [0.99154254]
 [0.00719979]]
[[0.0058377 ]
 [0.99206809]
 [0.99154366]
 [0.00719883]]
[[0.0058369 ]
 [0.99206916]
 [0.99154478]
 [0.00719786]]
[[0.0058361 ]
 [0.99207022]
 [0.99154589]
 [0.0071969 ]]
[[0.0058353 ]
 [0.99207128]
 [0.99154701]
 [0.00719593]]
[[0.0058345 ]
 [0.99207234]
 [0.99154812]
 [0.00719497]]
[[0.00583371]
 [0.9920734 ]
 [0.99154923]
 [0.00719401]]
[[0.00583291]
 [0.99207446]
 [0.99155035]
 [0.00719305]]
[[0.00583212]
 [0.99207552]
 [0

[[0.00535943]
 [0.99270299]
 [0.99220833]
 [0.00662463]]
[[0.00535901]
 [0.99270356]
 [0.99220891]
 [0.00662413]]
[[0.00535858]
 [0.99270412]
 [0.9922095 ]
 [0.00662362]]
[[0.00535816]
 [0.99270468]
 [0.99221008]
 [0.00662312]]
[[0.00535774]
 [0.99270524]
 [0.99221066]
 [0.00662261]]
[[0.00535732]
 [0.99270579]
 [0.99221125]
 [0.00662211]]
[[0.00535689]
 [0.99270635]
 [0.99221183]
 [0.00662161]]
[[0.00535647]
 [0.99270691]
 [0.99221241]
 [0.0066211 ]]
[[0.00535605]
 [0.99270747]
 [0.99221299]
 [0.0066206 ]]
[[0.00535563]
 [0.99270803]
 [0.99221358]
 [0.0066201 ]]
[[0.00535521]
 [0.99270859]
 [0.99221416]
 [0.00661959]]
[[0.00535479]
 [0.99270914]
 [0.99221474]
 [0.00661909]]
[[0.00535437]
 [0.9927097 ]
 [0.99221532]
 [0.00661859]]
[[0.00535395]
 [0.99271026]
 [0.9922159 ]
 [0.00661809]]
[[0.00535353]
 [0.99271081]
 [0.99221648]
 [0.00661759]]
[[0.00535311]
 [0.99271137]
 [0.99221706]
 [0.00661709]]
[[0.00535269]
 [0.99271192]
 [0.99221764]
 [0.00661659]]
[[0.00535227]
 [0.99271248]
 [0

[[0.00510953]
 [0.9930335 ]
 [0.99255235]
 [0.00632758]]
[[0.00510923]
 [0.99303389]
 [0.99255276]
 [0.00632723]]
[[0.00510894]
 [0.99303428]
 [0.99255316]
 [0.00632688]]
[[0.00510864]
 [0.99303467]
 [0.99255357]
 [0.00632653]]
[[0.00510835]
 [0.99303506]
 [0.99255397]
 [0.00632618]]
[[0.00510805]
 [0.99303545]
 [0.99255438]
 [0.00632583]]
[[0.00510776]
 [0.99303584]
 [0.99255478]
 [0.00632548]]
[[0.00510746]
 [0.99303623]
 [0.99255519]
 [0.00632513]]
[[0.00510717]
 [0.99303662]
 [0.99255559]
 [0.00632478]]
[[0.00510687]
 [0.99303701]
 [0.992556  ]
 [0.00632443]]
[[0.00510658]
 [0.9930374 ]
 [0.9925564 ]
 [0.00632409]]
[[0.00510629]
 [0.99303779]
 [0.99255681]
 [0.00632374]]
[[0.00510599]
 [0.99303818]
 [0.99255721]
 [0.00632339]]
[[0.0051057 ]
 [0.99303857]
 [0.99255761]
 [0.00632304]]
[[0.0051054 ]
 [0.99303896]
 [0.99255802]
 [0.00632269]]
[[0.00510511]
 [0.99303934]
 [0.99255842]
 [0.00632234]]
[[0.00510482]
 [0.99303973]
 [0.99255883]
 [0.00632199]]
[[0.00510452]
 [0.99304012]
 [0